name: movir_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  # dependency to can make icon for my app
  flutter_launcher_icons: ^0.13.1
  # Flutter plugin for reading and writing simple key-value pairs.
  shared_preferences: ^2.3.5
  # An SVG rendering and widget library for Flutter, which allows painting and displaying Scalable Vector Graphics 1.1 files.
  flutter_svg: ^2.0.9
  # firebase dependencies
  email_validator: ^3.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  # dependency for my services
  get_it: ^8.0.0
  # dependency for state managment
  flutter_bloc: ^8.1.6
  # dependency for svg picture image when used with non svg images
  flutter_svg_provider: ^1.0.7
  # dependency for handle bottom nav bar
  persistent_bottom_nav_bar: ^6.2.1

  #! firebase dependencies
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.1
  sign_in_with_apple: ^6.1.3
  crypto: ^3.0.6
  dio: ^5.8.0+1
  shimmer: ^3.0.0
  scroll_snap_list: ^0.9.1
  readmore: ^3.0.0
  sqflite: ^2.4.1
  path: ^1.9.0
  flutter_paypal_payment: ^1.0.8

#==================================  Dev  Dependencies  Section  ==============================
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 24 # android min sdk min:16, default 21
  adaptive_icon_background: "#21242C"
  adaptive_icon_foreground: "assets/images/logo.png"

  flutter_lints: ^4.0.0

#==================================  Flutter  Section Add Images and Fonts ==============================
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svgs/

  # To add assets to your application, add an assets section, like this:
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_24pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter_24pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_24pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter_24pt-Bold.ttf
          weight: 700

    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit-Regular.ttf
          weight: 400
        - asset: assets/fonts/Kanit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Kanit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Kanit-Bold.ttf
          weight: 700

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
#==================================  Generate  Flutter  Assets  Section  ==============================
flutter_assets:
  assets_path: assets/svgs/
  output_path: lib/core/utils/
  filename: app_assets.dart
