// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2A5Utge6wqoWulCESEArHvhH7oZWveDk',
    appId: '1:863551162558:web:9704fd6eed042ea6f336ef',
    messagingSenderId: '863551162558',
    projectId: 'movir-app-8bb89',
    authDomain: 'movir-app-8bb89.firebaseapp.com',
    storageBucket: 'movir-app-8bb89.firebasestorage.app',
    measurementId: 'G-XC23PN7XD6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzQ4ZroRH8Yo9V7qitNGsjTheY-cJEnN0',
    appId: '1:863551162558:android:3913a6521abf942bf336ef',
    messagingSenderId: '863551162558',
    projectId: 'movir-app-8bb89',
    storageBucket: 'movir-app-8bb89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5CETHQBW55HHB5XQB_GJdYdtOlu55fWE',
    appId: '1:863551162558:ios:38bf250e6cf5c47cf336ef',
    messagingSenderId: '863551162558',
    projectId: 'movir-app-8bb89',
    storageBucket: 'movir-app-8bb89.firebasestorage.app',
    iosBundleId: 'com.example.movirApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5CETHQBW55HHB5XQB_GJdYdtOlu55fWE',
    appId: '1:863551162558:ios:38bf250e6cf5c47cf336ef',
    messagingSenderId: '863551162558',
    projectId: 'movir-app-8bb89',
    storageBucket: 'movir-app-8bb89.firebasestorage.app',
    iosBundleId: 'com.example.movirApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2A5Utge6wqoWulCESEArHvhH7oZWveDk',
    appId: '1:863551162558:web:3290665497040062f336ef',
    messagingSenderId: '863551162558',
    projectId: 'movir-app-8bb89',
    authDomain: 'movir-app-8bb89.firebaseapp.com',
    storageBucket: 'movir-app-8bb89.firebasestorage.app',
    measurementId: 'G-5BHFYK87H7',
  );
}
